# Azure Developer CLI (azd) configuration for Prism
# Usage:
#   azd auth login
#   azd init (if not already initialized)
#   azd up     # provisions infrastructure AND deploys code
#   azd deploy # deploys code only (after infrastructure exists)
#
# For infrastructure only:
#   azd provision

name: prism
metadata:
  template: prism-document-intelligence

# Infrastructure configuration
infra:
  provider: bicep
  path: ./infra/bicep

# Service definitions - maps to Container Apps
services:
  backend:
    project: ./apps/api
    language: python
    host: containerapp
    docker:
      path: ./apps/api/Dockerfile
      context: .

  frontend:
    project: ./apps/web
    language: js
    host: containerapp
    docker:
      path: ./apps/web/Dockerfile
      context: ./apps/web

# Hooks for custom deployment steps
hooks:
  # Post-provision: Generate .env file for local development
  postprovision:
    shell: sh
    run: |
      echo ""
      echo "==================================================="
      echo "Prism infrastructure deployed successfully!"
      echo "==================================================="
      echo ""
      echo "Generating .env file for local development..."

      # Write .env file with provisioned values
      cat > .env << 'ENVEOF'
# Auto-generated by azd provision
# Environment: $AZURE_ENV_NAME
# Generated: $(date)

# Azure OpenAI / AI Foundry
AZURE_OPENAI_API_KEY=$AZURE_OPENAI_KEY
AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
AZURE_OPENAI_MODEL_NAME=$AZURE_OPENAI_MODEL_NAME
AZURE_OPENAI_API_VERSION=$AZURE_OPENAI_API_VERSION
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=$AZURE_OPENAI_CHAT_DEPLOYMENT_NAME
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=$AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME

# Azure AI Search
AZURE_SEARCH_ENDPOINT=$AZURE_SEARCH_ENDPOINT
AZURE_SEARCH_ADMIN_KEY=$AZURE_SEARCH_ADMIN_KEY

# Authentication
AUTH_PASSWORD=$AUTH_PASSWORD

# Monitoring (optional)
APPLICATIONINSIGHTS_CONNECTION_STRING=$APPLICATIONINSIGHTS_CONNECTION_STRING
ENVEOF
      # Now substitute the actual values
      envsubst < .env > .env.tmp && mv .env.tmp .env

      echo ""
      echo "Resources created:"
      echo "  Resource Group: ${AZURE_RESOURCE_GROUP}"
      echo "  Location: ${AZURE_LOCATION}"
      echo ""
      echo "Endpoints:"
      echo "  Azure OpenAI: ${AZURE_OPENAI_ENDPOINT}"
      echo "  Azure Search: ${AZURE_SEARCH_ENDPOINT}"
      echo ""
      echo ".env file created - you can now run locally with:"
      echo "  docker-compose -f infra/docker/docker-compose.yml --env-file .env up -d"
      echo ""
      echo "Or deploy to Azure Container Apps with:"
      echo "  azd deploy"
      echo ""

  # Pre-deploy: ensure Docker is running
  predeploy:
    shell: sh
    run: |
      if ! docker info > /dev/null 2>&1; then
        echo "Error: Docker is not running. Please start Docker and try again."
        exit 1
      fi

# Pipeline configuration for CI/CD
pipeline:
  provider: github
