#!/bin/bash
# Post-provision hook: Generate .env file for local development

echo ""
echo "==================================================="
echo "Prism infrastructure deployed successfully!"
echo "==================================================="
echo ""
echo "Generating .env file for local development..."

# Write .env file with provisioned values
cat > .env << EOF
# Auto-generated by azd provision
# Environment: ${AZURE_ENV_NAME}

# Azure OpenAI / AI Foundry
AZURE_OPENAI_API_KEY=${AZURE_OPENAI_KEY}
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
AZURE_OPENAI_MODEL_NAME=${AZURE_OPENAI_MODEL_NAME}
AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${AZURE_OPENAI_CHAT_DEPLOYMENT_NAME}
AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}

# Azure AI Search
AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
AZURE_SEARCH_ADMIN_KEY=${AZURE_SEARCH_ADMIN_KEY}

# Authentication
AUTH_PASSWORD=${AUTH_PASSWORD}

# Monitoring (optional)
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
EOF

echo ""
echo "Resources created:"
echo "  Resource Group: ${AZURE_RESOURCE_GROUP}"
echo "  Location: ${AZURE_LOCATION}"
echo ""
echo "Endpoints:"
echo "  Azure OpenAI: ${AZURE_OPENAI_ENDPOINT}"
echo "  Azure Search: ${AZURE_SEARCH_ENDPOINT}"
echo ""
echo ".env file created - you can now run locally with:"
echo "  docker-compose -f infra/docker/docker-compose.yml --env-file .env up -d"
echo ""
echo "Or deploy to Azure Container Apps with:"
echo "  azd deploy"
echo ""
